"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
dotenv_path = BASE_DIR / '.env' 

if dotenv_path.exists():
    load_dotenv(str(dotenv_path))
else:
    dotenv_path = BASE_DIR.parent / '.env'
    load_dotenv(str(dotenv_path))

# ==========================================
# SECURITY & ENVIRONMENT VARIABLES
# ==========================================

# SECRET_KEY from .env
SECRET_KEY = os.environ.get('SECRET_KEY')

# DEBUG from .env
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS from .env
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')
ALLOWED_HOSTS = allowed_hosts_env.split(',') if allowed_hosts_env else ['*']


# ==========================================
# APPLICATION DEFINITION
# ==========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'corsheaders',
    'rest_framework',
    # Local
    'rentals',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # must be first
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ==========================================
# DATABASE SETTINGS
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# ==========================================
# AUTHENTICATION & PASSWORDS
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_USER_MODEL = 'rentals.User'


# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# ==========================================
# DEFAULT AUTO FIELD
# ==========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ==========================================
# CORS SETTINGS
# ==========================================

# Safe by default: wide-open CORS is only convenient for local dev, so it
# defaults to DEBUG's value unless CORS_ALLOW_ALL_ORIGINS is set explicitly
# in .env. This keeps a production deploy (DEBUG=False) from silently
# inheriting an open-CORS policy just because it reused these settings.
cors_allow_all_env = os.environ.get('CORS_ALLOW_ALL_ORIGINS')
if cors_allow_all_env is not None:
    CORS_ALLOW_ALL_ORIGINS = cors_allow_all_env == 'True'
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

# Comma-separated list of allowed origins, used when CORS_ALLOW_ALL_ORIGINS
# is False, e.g. CORS_ALLOWED_ORIGINS=https://example.com,https://app.example.com
cors_allowed_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS')
CORS_ALLOWED_ORIGINS = cors_allowed_origins_env.split(',') if cors_allowed_origins_env else []

# ==========================================
# Static files
# ==========================================

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')