"""
Seed database with manga from AniList
Auto-generated by process_anilist_covers.py
"""
import os
import sys
import django

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from rentals.models import Manga, MangaCopy

def seed_anilist_manga():
    """Seed manga data from AniList"""

    print("Seeding manga from AniList...")

    mangas = [
    {
        "title": "Monster",
        "author": "Naoki Urasawa",
        "genre": "Drama, Mystery, Psychological, Thriller",
        "description": "Everyone faces uncertainty at some point in their lives. Even a brilliant surgeon like Kenzo Tenma is no exception. But there’s no way he could have known that his decision to stop chasing professional success and instead concentrate on his oath to save peoples’ lives would result in the birth of an abomination. The questions of good and evil now take on a terrifyingly real dimension. Years later, in Germany during the tumultuous post-reunification period, middle-aged childless couples are being",
        "cover_image_url": "/images/mangas/monster.jpg",
        "mbrs_id": 30001,
        "price": 19.0
    },
    {
        "title": "Berserk",
        "author": "Unknown",
        "genre": "Action, Adventure, Drama, Fantasy, Horror, Psychological",
        "description": "His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned—and anyone else foolish enough to oppose him! Accompanied by Puck the El",
        "cover_image_url": "/images/mangas/berserk.jpg",
        "mbrs_id": 30002,
        "price": 19.2
    },
    {
        "title": "20th Century Boys",
        "author": "Naoki Urasawa",
        "genre": "Drama, Mystery, Psychological, Sci-Fi, Thriller",
        "description": "Humanity, having faced extinction at the end of the 20th century, would not have entered the new millennium if it weren't for them. In 1969, during their youth, they created a symbol. In 1997, as the coming disaster slowly starts to unfold, that symbol returns. This is the story of a group of boys who try to save the world. For Kenji, a simple convenience store manager who once dreamed of becoming a rock 'n' roll musician, a host of memories from his past come rushing back when one of his childh",
        "cover_image_url": "/images/mangas/20th_century_boys.jpg",
        "mbrs_id": 30003,
        "price": 18.8
    },
    {
        "title": "Yokohama Kaidashi Kikou",
        "author": "Hitoshi Ashinano",
        "genre": "Sci-Fi, Slice of Life",
        "description": "Set hundreds of years in the future after an environmental catastrophe, Yokohama Kaidashi Kikou (also known as Yokohama Shopping Log) centers on the simple life of Alpha, an android who runs a small coffee shop in coastal Japan. Alpha stands witness to chronicle the end of humanity’s days with coffee, a slice of watermelon, and the sound of her moon guitar backed by distant seagulls. Quiet and bittersweet, this tale is about the melancholy beauty that can be found even as the end approaches. (So",
        "cover_image_url": "/images/mangas/yokohama_kaidashi_kikou.jpg",
        "mbrs_id": 30004,
        "price": 18.6
    },
    {
        "title": "Hajime no Ippo: Fighting Spirit!",
        "author": "George Morikawa",
        "genre": "Action, Comedy, Drama, Sports",
        "description": "Makunouchi Ippo has been bullied his entire life. Constantly running errands and being beaten up by his classmates, Ippo has always dreamed of changing himself, but never has the passion to act upon it. One day, in the midst of yet another bullying, Ippo is saved by Takamura Mamoru, who happens to be a boxer. Ippo faints from his injuries and is brought to Takamura boxing gym to recover. As he regains consciousness, he is awed and amazed at his new surroundings in the gym, though lacks confidenc",
        "cover_image_url": "/images/mangas/hajime_no_ippo_fighting_spirit!.jpg",
        "mbrs_id": 30007,
        "price": 18.7
    },
    {
        "title": "One Piece",
        "author": "Eiichirou Oda",
        "genre": "Action, Adventure, Comedy, Fantasy",
        "description": "As a child, Monkey D. Luffy was inspired to become a pirate by listening to the tales of the buccaneer \"Red-Haired\" Shanks. But his life changed when Luffy accidentally ate the Gum-Gum Devil Fruit and gained the power to stretch like rubber...at the cost of never being able to swim again! Years later, still vowing to become the king of the pirates, Luffy sets out on his adventure...one guy alone in a rowboat, in search of the legendary \"One Piece,\" said to be the greatest treasure in the world..",
        "cover_image_url": "/images/mangas/one_piece.jpg",
        "mbrs_id": 30013,
        "price": 19.1
    },
    {
        "title": "Fullmetal Alchemist",
        "author": "Hiromu Arakawa",
        "genre": "Action, Adventure, Comedy, Drama, Fantasy",
        "description": "Alchemy tore the Elric brothers’ bodies apart. Can their bond make them whole again? In this world, alchemists are those who study and perform the art of alchemical transmutation—the science of manipulating and transforming matter. They are bounded by the Law of Equivalent Exchange: in order to gain something, one must sacrifice something of equal value. In an alchemical ritual gone wrong, Edward Elric lost his arm and his leg, and his brother Alphonse became nothing but a soul in a suit of armo",
        "cover_image_url": "/images/mangas/fullmetal_alchemist.jpg",
        "mbrs_id": 30025,
        "price": 18.9
    },
    {
        "title": "Hunter x Hunter",
        "author": "Yoshihiro Togashi",
        "genre": "Action, Adventure, Comedy, Fantasy",
        "description": "Gon might be a country boy, but he has high aspirations. Despite his Aunt Mito's protests, Gon decides to follow in his father's footsteps and become a legendary Hunter. The Hunter hopefuls begin their journey by storm-tossed ship, where Gon meets Leorio and Kurapika, the only other applicants who aren't devastated by bouts of seasickness. Having survived the terrors of the high seas, Gon and his companions now have to prove their worth in a variety of tests in order to find the elusive Exam Hal",
        "cover_image_url": "/images/mangas/hunter_x_hunter.jpg",
        "mbrs_id": 30026,
        "price": 18.8
    },
    {
        "title": "Nana",
        "author": "Ai Yazawa",
        "genre": "Drama, Music, Romance, Slice of Life",
        "description": "Nana Komatsu is a young woman who's endured an unending string of boyfriend problems. Moving to Tokyo, she's hoping to take control of her life and put all those messy misadventures behind her. She's looking for love and she's hoping to find it in the big city. Nana Osaki, on the other hand, is cool, confident and focused. She swaggers into town and proceeds to kick down the doors to Tokyo's underground punk scene. She's got a dream and won't give up until she becomes Japan's No. 1 rock'n'roll s",
        "cover_image_url": "/images/mangas/nana.jpg",
        "mbrs_id": 30028,
        "price": 18.8
    },
    {
        "title": "Gin Tama",
        "author": "Hideaki Sorachi",
        "genre": "Action, Comedy, Drama, Sci-Fi",
        "description": "The samurai didn't stand a chance. First, the aliens invaded Japan. Next, they took all the jobs. And then they confiscated everyone's swords. So what does a hotheaded former samurai like Sakata \"Gin\" Gintoki do to make ends meet? Take any odd job that comes his way, even if it means losing his dignity. (Source: VIZ Media) Included Bonus Chapters: Volume 1: Dandelion (One-shot). Volume 2: Shirokuro (One-shot). Volume 24: 13 (One-shot). Volume 38: Bankara-san Ga Tooru (One-shot). Volume 41: Speci",
        "cover_image_url": "/images/mangas/gin_tama.jpg",
        "mbrs_id": 30044,
        "price": 18.6
    },
    {
        "title": "Slam Dunk",
        "author": "Takehiko Inoue",
        "genre": "Comedy, Drama, Sports",
        "description": "Hanamichi Sakuragi's got no game with girls--none at all! It doesn't help that he's known for throwing down at a moment's notice and always coming out on top. A hopeless bruiser, he's been rejected by 50 girls in a row! All that changes when he meets the girl of his dreams, Haruko, and she's actually not afraid of him! When she introduces him to the game of basketball, his life is changed forever... (Source: VIZ Media)",
        "cover_image_url": "/images/mangas/slam_dunk.jpg",
        "mbrs_id": 30051,
        "price": 19.0
    },
    {
        "title": "Aria",
        "author": "Kozue Amano",
        "genre": "Adventure, Comedy, Drama, Fantasy, Sci-Fi, Slice of Life",
        "description": "On the planet Aqua, a world once known as Mars, Akari Mizunashi has just made her home in the town of Neo-Venezia, a futuristic imitation of the ancient city of Venice. In pursuit of her dream to become an Undine — a gondolier who leads high-end tours around the city — Akari joins as a trainee with the Aria Company, one of the three most prestigious water-guide companies in Neo-Venezia. There, she explores the beauty of the city and the world along with other trainees from Aria and rival compani",
        "cover_image_url": "/images/mangas/aria.jpg",
        "mbrs_id": 30081,
        "price": 18.6
    },
    {
        "title": "Fruits Basket",
        "author": "Natsuki Takaya",
        "genre": "Comedy, Drama, Psychological, Romance, Supernatural",
        "description": "After a family tragedy turns her life upside down, plucky high schooler Tohru Honda takes matters into her own hands and moves out...into a tent! Unfortunately for her, she pitches her new home on private land belonging to the mysterious Sohma clan, and it isn't long before the owners discover her secret. But, as Tohru quickly finds out when the family offers to take her in, the Sohmas have a secret of their own--when touched by the opposite sex, they turn into the animals of the Chinese Zodiac!",
        "cover_image_url": "/images/mangas/fruits_basket.jpg",
        "mbrs_id": 30102,
        "price": 18.5
    },
    {
        "title": "Yotsuba&!",
        "author": "Kiyohiko Azuma",
        "genre": "Comedy, Slice of Life",
        "description": "Hello! This is Koiwai Yotsuba, Yotsuba Koiwai...um, YOTSUBA! Yotsuba moved with Daddy to a new house from our old house waaaaaaay over there! And moving's fun 'cos people wave! (Ohhhh!!) And Yotsuba met these nice people next door and made friends to play with (one of 'em acted like one of those bad strangers Daddy told Yotsuba not to go with, but it was okay in the end). I hope we get to play a lot. And eat ice cream! And-and-and...oh yeah! You should come play with Yotsuba too! (Source: Yen Pr",
        "cover_image_url": "/images/mangas/yotsuba&!.jpg",
        "mbrs_id": 30104,
        "price": 18.8
    },
    {
        "title": "BECK",
        "author": "Harold Sakuishi",
        "genre": "Comedy, Drama, Music, Romance, Slice of Life",
        "description": "For the first 14 years of his life, Yukio Tanaka has been one heck of a boring guy. He has no hobbies, a weak taste in music, and only a small vestige of a personality. He yearns for an exciting life, but his shy, and somewhat neurotic personality make him his own worst enemy. Little does he know that his life will be forever changed when he meets Ryusuke Minami, a wild and unpredictable 16 year-old fresh from America, who happens to be in a rock-and-roll band named after his Frankenstein-like p",
        "cover_image_url": "/images/mangas/beck.jpg",
        "mbrs_id": 30145,
        "price": 18.6
    },
    {
        "title": "GTO: Great Teacher Onizuka",
        "author": "Tooru Fujisawa",
        "genre": "Action, Comedy, Drama, Ecchi",
        "description": "Former juvenile delinquent Onizuka finds himself thrust into to role of high school teacher, facing students who behave just as he used to and an administration that doesn't trust him. Using the brash an unorthodox methods he picked up in his youth, Onizuka manages to reach through to his kids and help them with their problems. (Source: TOKYOPOP) Notes: - Won the 22nd Kodansha Manga Award for Best Shounen Manga. - The chapter count includes the 7 chapters extra GTO: Great Toroko Oppai♡ (Tomoko's",
        "cover_image_url": "/images/mangas/gto_great_teacher_onizuka.jpg",
        "mbrs_id": 30336,
        "price": 18.6
    },
    {
        "title": "Mushishi",
        "author": "Yuki Urushibara",
        "genre": "Drama, Fantasy, Mystery, Slice of Life, Supernatural",
        "description": "Some live in the deep darkness behind your eyelids. Some eat silence. Some thoughtlessly kill. Some simply drive men mad. They are known as mushi—creatures that came into being shortly after life emerged from the primordial ooze. They still exist parallel to our own lives and can only be seen by a select few. As a mushishi, Ginko is one of the few who are aware of their existence, and this young man with a sardonic smile roams from place to place with the knowledge and skill to aid those unwitti",
        "cover_image_url": "/images/mangas/mushishi.jpg",
        "mbrs_id": 30418,
        "price": 18.5
    },
    {
        "title": "Vinland Saga",
        "author": "Makoto Yukimura",
        "genre": "Action, Adventure, Drama",
        "description": "As a child, Thorfinn sat at the feet of the great Leif Ericson and thrilled to wild tales of a land far to the west. But his youthful fantasies were shattered by a mercenary raid. Raised by the Vikings who murdered his father, Thorfinn became a terrifying warrior, forever seeking to kill the band's leader, Askeladd, and avenge his father. Sustaining Thorfinn through his ordeal are his pride in his family and his dreams of a fertile westward land, a land without war or slavery … the land Leif cal",
        "cover_image_url": "/images/mangas/vinland_saga.jpg",
        "mbrs_id": 30642,
        "price": 19.0
    },
    {
        "title": "Nausicaä of the Valley of the Wind",
        "author": "Hayao Miyazaki",
        "genre": "Action, Adventure, Drama, Fantasy, Sci-Fi",
        "description": "Humanity, in its hubris, has precipitated a devastating environmental disaster. Flourishing industrial civilizations have been swallowed up by the Sea of Corruption, an enormous forest of fungi releases a miasma of poisonous spores into the air. Nausicaa, a compassionate young princess, and her allies battle to heal a wounded world and its inhabitants... (Source: VIZ Media) Note: Won the 26th Seiun Award for Best Comic (1995).",
        "cover_image_url": "/images/mangas/nausicaä_of_the_valley_of_the_wind.jpg",
        "mbrs_id": 30651,
        "price": 18.5
    },
    {
        "title": "The Horizon",
        "author": "Ji-Hun Jeong",
        "genre": "Adventure, Drama, Psychological",
        "description": "A world where everything has been lost. A boy and a girl alone together. A spark of hope kindled between them. All they can do is move forward. But against broken adults and devastating despair, how long will they be able to keep going...? (Source: Yen Press)",
        "cover_image_url": "/images/mangas/the_horizon.jpg",
        "mbrs_id": 100568,
        "price": 18.5
    },
    {
        "title": "Here U Are",
        "author": "DJUN",
        "genre": "Drama, Romance, Slice of Life",
        "description": "Sophomore Yu Yang is a real treasure. He has a cheerful, easy-going, and emphatic personality. Seniors look up to him, and he knows how to stand up for himself. Freshman Li Huan is moody and taciturn, haughty and, at times, outright rude. How will these two manage to get along, and where will it lead them..? (Source: Aloha Comics) Note: Includes 20 extra chapters.",
        "cover_image_url": "/images/mangas/here_u_are.jpg",
        "mbrs_id": 100805,
        "price": 18.5
    },
    {
        "title": "Chainsaw Man",
        "author": "Tatsuki Fujimoto",
        "genre": "Action, Comedy, Drama, Horror, Supernatural",
        "description": "The name says it all! Denji's life of poverty is changed forever when he merges with his pet chainsaw dog, Pochita! Now he's living in the big city and an official Devil Hunter. But he's got a lot to learn about his new job and chainsaw powers! (Source: MANGA Plus) Notes: - Nominated for the 2020 Manga Taisho Award. - Winner of the 2021 Kono Manga ga Sugoi Award. - Winner of the 66th Shogakukan Manga Award in the shounen category. - Winner of the 2021 and 2022 Harvey Award for Best Manga. - Chap",
        "cover_image_url": "/images/mangas/chainsaw_man.jpg",
        "mbrs_id": 105778,
        "price": 18.5
    },
    {
        "title": "Ikoku Nikki",
        "author": "Tomoko Yamashita",
        "genre": "Drama, Slice of Life",
        "description": "The manga centers on 35-year-old novelist Makio Koudai and her 15-year-old niece Asa, who live together under one roof. Makio took Asa in on a sudden impulse after Asa's parents, which included Makio's older sister, passed away. The next day, Makio returns to her senses and remembers that she does not do well in the company of other people. So begins their daily life, as Makio attempts to acclimate to a roommate, while Asa attempts to get used to an adult that never acts like one. (Source: Anime",
        "cover_image_url": "/images/mangas/ikoku_nikki.jpg",
        "mbrs_id": 106331,
        "price": 18.7
    },
    {
        "title": "Eleceed",
        "author": "Jae-Ho Son",
        "genre": "Action, Comedy, Supernatural",
        "description": "Ji-U is a kind-hearted young man who harnesses the lightning quick reflexes of a cat to secretly make the world a better place – one saved little child or foster pet at a time. Kayden is a secret agent on the run, who finds himself stuck in the body of a…um…decidedly fat old fluffy cat. Together, armed with Ji-U’s super powers and Kayden’s uber-smarts, they’re out to fight those forces who would let evil rule this world. That is, if they can stand each other long enough to get the job done. (Sou",
        "cover_image_url": "/images/mangas/eleceed.jpg",
        "mbrs_id": 106929,
        "price": 18.5
    },
    {
        "title": "Blue Period",
        "author": "Tsubasa Yamaguchi",
        "genre": "Drama, Slice of Life",
        "description": "The studious Yatora leaves a dry life of study and good manners behind for a new passion: painting. But untethering yourself from all your past expectations is dangerous as well as thrilling… (Source: Kodansha USA) Note: Nominated for Manga Taisho Awards in 2019, Kodansha Manga Awards in 2019 and the 24th Tezuka Osamu Cultural Prize in 2020. Winner of the 13th Manga Taisho Awards. Winner of the General Manga category of the 44th annual Kodansha Manga Awards.",
        "cover_image_url": "/images/mangas/blue_period.jpg",
        "mbrs_id": 107237,
        "price": 18.6
    },
    {
        "title": "Aoashi",
        "author": "Yuugo Kobayashi",
        "genre": "Sports",
        "description": "Ashito Aoi, a third year middle school student from Ehime, meets Fukuda Tatsuya, a J Youth League coach. Even though he's still rough around the edges, Ashito has such amazing potential that he gets invited by coach Fukuda to participate in his team's try-outs in Tokyo. The story of a boy who will revolutionize Japanese football begins to unfold. Notes: - Nominated for the 2017 Manga Taishou Award. - Winner of the 65th Shogakukan Manga Award for \"Best General Manga\" category in 2019.",
        "cover_image_url": "/images/mangas/aoashi.jpg",
        "mbrs_id": 107279,
        "price": 18.6
    },
    {
        "title": "Skip and Loafer",
        "author": "Misaki Takamatsu",
        "genre": "Comedy, Romance, Slice of Life",
        "description": "Excellent student Iwakura Mitsumi has always dreamt about leaving her small town, going to a prestigious university, and making positive change in the world. But she’s so focused on reaching her goals that she’s not prepared for the very different (and overwhelming) city life that awaits her in a Tokyo high school. Luckily, she makes fast friends with Shima Sousuke, a handsome classmate who’s as laid-back as she is over-prepared. Can this naive country girl make it big in Tokyo with Sousuke by h",
        "cover_image_url": "/images/mangas/skip_and_loafer.jpg",
        "mbrs_id": 109285,
        "price": 18.6
    },
    {
        "title": "Heaven Official's Blessing",
        "author": "Mo Xiang Tong Xiu",
        "genre": "Adventure, Drama, Fantasy, Romance",
        "description": "800 years ago, Xie Lian was a pure-blooded and noble Crown Prince, a well-regarded child of Heaven with unlimited potential. But who knew that, after he ascended and became a god with tens of thousands of worshippers, his fate would take such a sharp downhill turn? He was demoted again and again, and fell to rock bottom. 800 years later, Xie Lian ascended again, but this time, without worshippers or and without incense. One day, after returning from collecting scraps, he took a mysterious young ",
        "cover_image_url": "/images/mangas/heaven_official's_blessing.jpg",
        "mbrs_id": 112275,
        "price": 18.7
    },
    {
        "title": "Bungo Stray Dogs Beast",
        "author": "Kafka Asagiri",
        "genre": "Action, Drama, Mystery, Supernatural",
        "description": "In a parallel universe of Bungo Stray Dogs, Ryuunosuke Akutagawa’s desperate mission to save his younger sister leads to him being recruited by the armed detective agency! (Source: Yen Press)",
        "cover_image_url": "/images/mangas/bungo_stray_dogs_beast.jpg",
        "mbrs_id": 114998,
        "price": 18.5
    },
    {
        "title": "Veil",
        "author": "Ikumi Fukuda",
        "genre": "Romance, Slice of Life",
        "description": "A chance encounter. A handsome soldier. A beautiful woman. A tentative love affair smolders on the snowy cobblestone streets, out of sight of those that might keep them apart. Veil is a beautifully illustrated full-color romance manga, told in stylish short vignettes, beautiful illustrations, and secret moments. (Source: Udon Entertainment, edited)",
        "cover_image_url": "/images/mangas/veil.jpg",
        "mbrs_id": 116170,
        "price": 18.7
    },
    {
        "title": "The Summer You Were There",
        "author": "Yuama",
        "genre": "Drama, Psychological, Romance",
        "description": "Shizuku is a shy girl who hardly talks to other people. Instead, she loses herself in creative writing, crafting a novel that she never plans to show anyone. But when Kaori–Shizuku’s cute, popular classmate–gets her hands on Shizuku’s manuscript, everything changes. Kaori is a huge fan, and suggests that Shizuku can get inspiration for her writing if the two of them start dating! Can these very different young ladies create their own love story together? (Source: Seven Seas Entertainment)",
        "cover_image_url": "/images/mangas/the_summer_you_were_there.jpg",
        "mbrs_id": 117620,
        "price": 18.7
    },
    {
        "title": "Medalist",
        "author": "Ikada Tsuruma",
        "genre": "Drama, Psychological, Sports",
        "description": "Inori is a little girl who dreams of becoming a figure skater. Yet, the obstacles to this dream feel insurmountable: Inori’s already “too old” (she’s 11); she’s always had trouble at school; and, worst of all, her older sister’s skating dreams ended in failure, so her mother is dead set against putting her other daughter through a similar experience. Still, the rink is the only place Inori can be herself, and she’s out on the ice when a fateful meeting takes place. Tsukasa, a frustrated coach on",
        "cover_image_url": "/images/mangas/medalist.jpg",
        "mbrs_id": 118371,
        "price": 18.7
    },
    {
        "title": "Frieren: Beyond Journey’s End",
        "author": "Kanehito Yamada",
        "genre": "Adventure, Drama, Fantasy",
        "description": "The adventure is over but life goes on for an elf mage just beginning to learn what living is all about. Elf mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. With the great struggle over, they all go their separate ways to live a quiet life. But as an elf, Frieren, nearly immortal, will long outlive the rest of her former party. How will she come to terms with the mortality of her friends? How can she find fulfillment in her own life,",
        "cover_image_url": "/images/mangas/frieren_beyond_journey’s_end.jpg",
        "mbrs_id": 118586,
        "price": 18.7
    },
    {
        "title": "Uma Musume: Cinderella Gray",
        "author": "Pierre Sugiura",
        "genre": "Drama, Sports",
        "description": "Uma Musume Cinderella Gray is a spin-off title of the Uma Musume project by Cygames. It follows Oguri Cap through her time at Kasamatsu Training Center Academy and on her journey of becoming a legendary horse girl. Note: Includes the one-shot \"Uma Musume: Cinderella Gray Gaiden - The mermaid left behind\".",
        "cover_image_url": "/images/mangas/uma_musume_cinderella_gray.jpg",
        "mbrs_id": 119247,
        "price": 18.9
    },
    {
        "title": "Omniscient Reader",
        "author": "UMI",
        "genre": "Action, Adventure, Fantasy",
        "description": "Back then, Dok-Ja had no idea. He had no idea his favorite web novel 'Three Ways to Survive the Apocalypse' was going to come to life, and that he would become the only person to know how the world was going to end. He also had no idea he would end up becoming the protagonist of this novel-turned-reality. Now, Dok-Ja will go on a journey to change the course of the story and save humankind once and for all. (Source: WEBTOON, edited)",
        "cover_image_url": "/images/mangas/omniscient_reader.jpg",
        "mbrs_id": 119257,
        "price": 18.6
    },
    {
        "title": "The Legend of the Northern Blade",
        "author": "Hae-Min",
        "genre": "Action, Adventure, Fantasy",
        "description": "For decades, the brave warriors of the Northern Heavenly Sect fought to keep the world safe from the evil Silent Night. But when the fourth generation leader is accused of colluding with the enemy, he is forced to disband the sect and commit suicide to protect his son, Moo-Won. With no family and allies left, Moo-Won leads a dreary life under close surveillance... until a surprise attack from the Silent Night gives him a chance to escape to the mountains. There, the young warrior trains to maste",
        "cover_image_url": "/images/mangas/the_legend_of_the_northern_blade.jpg",
        "mbrs_id": 119521,
        "price": 18.5
    },
    {
        "title": "Seasons of Blossom",
        "author": "HONGDUCK",
        "genre": "Comedy, Drama, Romance",
        "description": "Oh, to be young and in love. Oh, to be wild and carefree. The springtime of life is intense, tumultuous, and at times, oh so confusing. Spring, summer, fall and winter -- love blossoms in all seasons. (Source: WEBTOON)",
        "cover_image_url": "/images/mangas/seasons_of_blossom.jpg",
        "mbrs_id": 121565,
        "price": 18.5
    },
    {
        "title": "Jibi Eopseo",
        "author": "Wanan",
        "genre": "Comedy, Drama, Slice of Life, Supernatural",
        "description": "Hae-Jun Go, who ran from home, and Eun-Yeong Baek, the problem child who lives in a tent. These two, who met under terrible circumstances, are forced to live together in an abandoned dormitory. This is a story of difficult growth between two people who hate both the dorm and each other. (Source: Naver, translated)",
        "cover_image_url": "/images/mangas/jibi_eopseo.jpg",
        "mbrs_id": 126986,
        "price": 18.6
    },
    {
        "title": "Hirayasumi",
        "author": "Keigo Shinzo",
        "genre": "Comedy, Drama, Slice of Life",
        "description": "With a carefree outlook on life, Hiroto knows better than anyone that slowing down is sometimes the best way to move forward. At 29 years old, carefree Hiroto Ikuta doesn’t have a girlfriend, a full-time job, or a plan for the future—and he couldn’t be happier. Hiroto’s breezy attitude isn’t easy for everyone to understand, though. In a world filled with anxiety, confusion, and grief, Hiroto and the people who surround him are all just doing their best to figure out this thing called life. After",
        "cover_image_url": "/images/mangas/hirayasumi.jpg",
        "mbrs_id": 132288,
        "price": 18.5
    },
    {
        "title": "Vagabond: Saigo no Manga-ten",
        "author": "Takehiko Inoue",
        "genre": "Action, Drama, Psychological",
        "description": "Telling the later life of Vagabond's Musashi Miyamoto, it was depicted through 140 hand-drawn drawings with ink and brush. It was released at the Ueno Royal Museum in Tokyo in May 2008, and since then it has been displayed at three other venues, Kumamoto City Museum, Suntory Museum in Osaka, and Sendai Mediatheque, with new paintings and productions. Note: The comic was compiled in two books: \"Inoueno: Mikazuki-hen\" (いのうえの 三日月篇) and \"Inoueno: Mangetsu-hen\" (いのうえの 満月篇).",
        "cover_image_url": "/images/mangas/vagabond_saigo_no_manga-ten.jpg",
        "mbrs_id": 135129,
        "price": 18.8
    },
    {
        "title": "The Moon on a Rainy Night",
        "author": "Kuzushiro",
        "genre": "Drama, Romance, Slice of Life",
        "description": "One day, while rushing to a piano lesson, a girl named Saki collides with someone on the street. As Saki collects herself, the stranger picks up the sheet music Saki dropped, hands it to Saki together with a band-aid, and continues on her way—all without saying a word. Saki is left wondering about the identity of the tall, lovely stranger, only to discover the next day that she is one of her classmates at her new high school. The girl’s name is Kanon, and though she is hearing impaired, she refu",
        "cover_image_url": "/images/mangas/the_moon_on_a_rainy_night.jpg",
        "mbrs_id": 136109,
        "price": 18.6
    },
    {
        "title": "The Greatest Estate Developer",
        "author": "Hyeon-Min Lee",
        "genre": "Adventure, Comedy, Fantasy",
        "description": "When civil engineering student Su-Ho Kim falls asleep reading a fantasy novel, he wakes up as a character in the book! Su-Ho is now in the body of Lloyd Frontera, a lazy noble who loves to drink, and whose family is in a mountain of debt. Using his engineering knowledge, Su-Ho designs inventions to avert the terrible future that lies in wait for him. With the help of a giant hamster, a knight, and the world’s magic, can Su-Ho dig his new family out of debt and build a better future? (Source: WEB",
        "cover_image_url": "/images/mangas/the_greatest_estate_developer.jpg",
        "mbrs_id": 140407,
        "price": 19.0
    },
    {
        "title": "The Fragrant Flower Blooms With Dignity",
        "author": "Saka Mikami",
        "genre": "Comedy, Drama, Romance",
        "description": "This story takes place in a particular town with two infamous schools in constant dispute: Chidori High, a boys' school predominantly attended by low-class students with damning grades, and its neighbor Kikyo Girls' High, with most of its female students coming from wealthy and prestigious families. One day, high school second-year Rintaro Tsumugi, a fierce-looking but gentle-minded student at Chidori, is helping at his family's patisserie when he encounters a female customer by the name of Kaor",
        "cover_image_url": "/images/mangas/the_fragrant_flower_blooms_with_dignity.jpg",
        "mbrs_id": 140475,
        "price": 18.7
    },
    {
        "title": "Goodbye, Eri",
        "author": "Tatsuki Fujimoto",
        "genre": "Drama, Psychological",
        "description": "With his mother dying, Yuuta attempts to capture her last days on his phone. After her death, Yuuta heads to the roof of the hospital to commit suicide, but a meeting with a strange girl leads him on the path to making a movie. (Source: Manga Plus)Note: The one-shot was compiled in a special volume, released on July 4, 2022.",
        "cover_image_url": "/images/mangas/goodbye,_eri.jpg",
        "mbrs_id": 146983,
        "price": 18.5
    },
    {
        "title": "The Ramparts of Ice",
        "author": "Koucha Agasawa",
        "genre": "Comedy, Drama, Romance, Slice of Life",
        "description": "Koyuki Hikawa isn't great with people and always puts up a wall between others. She had been spending her high school days alone, but one day meets the overly friendly Minato Amamiya. The loner, Koyuki, the popular girl, Miki, the guy with no personal space, Minato, and the laid back member of the basketball team, Yota... The story of these four somewhat awkward students in their bloom of youth begins! (Source: MangaPlaza)",
        "cover_image_url": "/images/mangas/the_ramparts_of_ice.jpg",
        "mbrs_id": 166742,
        "price": 18.5
    },
    {
        "title": "Our Sunny Days",
        "author": "Seok-Chan Jeong",
        "genre": "Romance, Slice of Life",
        "description": "Sung Ho’s not the kind you’d typically expect to settle down in the countryside. He’s in his late 20s, ex-military, and…a single father with a year-old baby his ex-girlfriend pawned off on him. Jobless and without any prospects but a house, Sung Ho hopes the peaceful Nuldongmae village will make a good new home for him and his daughter. Rumor has it that the head of the village, despite his young age, is a real jerk… But he won’t have to deal with that, will he? But on the very day he moves in, ",
        "cover_image_url": "/images/mangas/our_sunny_days.jpg",
        "mbrs_id": 168509,
        "price": 18.5
    },
    {
        "title": "Kimi ni Okuru Eien",
        "author": "Yuama",
        "genre": "Drama, Psychological, Romance",
        "description": "Bonus after story that was included with the special edition of volume 6 of Kimi to Tsuzuru Utakata.",
        "cover_image_url": "/images/mangas/kimi_ni_okuru_eien.jpg",
        "mbrs_id": 174875,
        "price": 18.6
    },
    {
        "title": "The Knight Only Lives Today",
        "author": "Hyeon-Min Lee",
        "genre": "Action, Fantasy",
        "description": "Is dying repeatedly a blessing? Enkrid's life-long dream of becoming a knight looked to be forever out of reach, until one day he died... and woke up at the beginning of that same day! Now that he has unlimited chances to train and engage in mortal combat, just how far can he go?(Source: WEBTOON)",
        "cover_image_url": "/images/mangas/the_knight_only_lives_today.jpg",
        "mbrs_id": 177706,
        "price": 18.5
    },
    {
        "title": "On the Way to Meet Mom",
        "author": "Gomyang",
        "genre": "Adventure, Fantasy",
        "description": "One day, after being discovered in an abandoned house by a rescue team, Mori suddenly finds himself in a children's protection center. Here, he begins to learn a new way of life – one that includes grand care packages sent by a mysterious patron. But when his closest friend is reunited with her mother and leaves the center, Mori learns for the first time the existence of a mother for every child, and decides to embark on a journey to find his own. But what sort of obstacles wait along the way?(S",
        "cover_image_url": "/images/mangas/on_the_way_to_meet_mom.jpg",
        "mbrs_id": 187189,
        "price": 18.8
    },
    {
        "title": "My Bias Gets on the Last Train",
        "author": "JIXKSEE",
        "genre": "Drama, Romance",
        "description": "Every night, Yeo-Un takes the last train home—same route, same time, same routine. But one thing keeps catching his eye: a girl with a guitar and a presence that lingers in his mind. When a shared love for the indie band Long Afternoon sparks a conversation, their late-night encounters begin to turn into something more. But Hae-In isn’t just another fan—she’s the voice behind the band, a secret she can’t afford to reveal. As music draws them closer, the truth may threaten to pull them apart. Whe",
        "cover_image_url": "/images/mangas/my_bias_gets_on_the_last_train.jpg",
        "mbrs_id": 187944,
        "price": 18.5
    },
    {
        "title": "Vagabond",
        "author": "Takehiko Inoue",
        "genre": "Action, Adventure, Drama",
        "description": "At seventeen years of age, Miyamoto Musashi--still known by his childhood name, Shinmen Takezo--was a wild young brute just setting out along the way of the sword. In the aftermath of the epic Battle of Sekigahara, Takezo finds himself a fugitive survivor on the losing side of the war. Takezo's vicious nature has made him an outcast even in his own village, and he is hunted down like an animal. At this crucial crossroads in Takezo's life, an eccentric monk and a childhood friend are the only one",
        "cover_image_url": "/images/mangas/vagabond.jpg",
        "mbrs_id": 30656,
        "price": 19.1
    },
    {
        "title": "Real",
        "author": "Takehiko Inoue",
        "genre": "Drama, Psychological, Sports",
        "description": "A motorcycle accident, bone cancer, a speeding truck crashing into a boy on a stolen bicycle--tragic life-changing events turn the worlds of three young men upside down. These three very different personalities have only one thing in common--their passion for basketball. (Source: VIZ Media) Note: Won an Excellence Prize for manga at the 2001 Japan Media Arts Festival.",
        "cover_image_url": "/images/mangas/real.jpg",
        "mbrs_id": 30657,
        "price": 18.9
    },
    {
        "title": "Neon Genesis Evangelion",
        "author": "Yoshiyuki Sadamoto",
        "genre": "Action, Drama, Mecha, Mystery, Psychological, Sci-Fi",
        "description": "In 2015, the \"Angels\" have returned, and Shinji Ikari, a fourteen year-old child of the new Earth, is forced by his father Gendo--commander of the secret organization NERV--to pilot the monstrous biomechanical weapon called \"Evangelion\" to match the Angels' fearsome power... (Source: VIZ Media)",
        "cover_image_url": "/images/mangas/neon_genesis_evangelion.jpg",
        "mbrs_id": 30698,
        "price": 18.4
    },
    {
        "title": "Pluto",
        "author": "Naoki Urasawa",
        "genre": "Drama, Mecha, Mystery, Psychological, Sci-Fi",
        "description": "In an ideal world where man and robots coexist, someone or something has destroyed the powerful Swiss robot Mont Blanc. Elsewhere a key figure in a robot rights group is murdered. The two incidents appear to be unrelated...except for one very conspicuous clue - the bodies of both victims have been fashioned into some sort of bizarre collage complete with makeshift horns placed by the victims' heads. Interpol assigns robot detective Gesicht to this most strange and complex case - and he eventuall",
        "cover_image_url": "/images/mangas/pluto.jpg",
        "mbrs_id": 30745,
        "price": 18.5
    },
    {
        "title": "Banana Fish",
        "author": "Akimi Yoshida",
        "genre": "Action, Adventure, Drama, Psychological, Thriller",
        "description": "Nature made Ash Lynx beautiful; nurture made him a cold ruthless killer. A runaway brought up as the adopted heir and sex toy of \"Papa\" Dino Golzine, Ash, now at the rebellious age of seventeen, forsakes the kingdom held out by the devil who raised him. But the hideous secret that drove Ash's older brother mad in Vietnam has suddenly fallen into Papa's insatiably ambitious hands--and it's exactly the wrong time for Eiji Okamura, a pure-hearted young photographer from Japan, to make Ash Lynx's ac",
        "cover_image_url": "/images/mangas/banana_fish.jpg",
        "mbrs_id": 30756,
        "price": 18.5
    },
    {
        "title": "Lone Wolf and Cub",
        "author": "Kazuo Koike",
        "genre": "Action, Drama",
        "description": "An epic samurai adventure of staggering proportions—over 7000 pages—Lone Wolf and Cub (Kozure Okami in Japan) is acknowledged worldwide for the brilliant writing of series creator Kazuo Koike and the groundbreaking cinematic visuals of the late Goseki Kojima, creating unforgettable imagery of stark beauty, kinetic fury, and visceral thematic power that influenced a generation of visual storytellers both in Japan and in the West. (Source: Dark Horse)",
        "cover_image_url": "/images/mangas/lone_wolf_and_cub.jpg",
        "mbrs_id": 30904,
        "price": 18.5
    },
    {
        "title": "Dorohedoro",
        "author": "Q Hayashida",
        "genre": "Action, Adventure, Comedy, Fantasy, Horror, Mystery",
        "description": "In a city so dismal it's known only as \"the Hole,\" a clan of Sorcerers have been plucking people off the streets to use as guinea pigs for atrocious \"experiments\" in the black arts. In a dark alley, Nikaido found Caiman, a man with a reptile head and a bad case of amnesia. To undo the spell, they're hunting and killing the Sorcerers in the Hole, hoping that eventually they'll kill the right one. But when En, the head Sorcerer, gets word of a lizard-man slaughtering his people, he sends a crew of",
        "cover_image_url": "/images/mangas/dorohedoro.jpg",
        "mbrs_id": 31133,
        "price": 18.6
    },
    {
        "title": "March Comes in Like a Lion",
        "author": "Chica Umino",
        "genre": "Drama, Slice of Life",
        "description": "Rei Kiriyama is a child prodigy. Rei Kiriyama is also an orphan who lives alone in an empty apartment. Rei Kiriyama is a teen working in an adult's world. Life is complicated for Rei. He's an up-and-coming shogi player on the verge of turning pro, but he has no homelife, or much of a life period, outside his board game, but thankfully with the help of some life-long friends he has an opportunity start all over again. (Source: DENPA) Notes: - Winner of the Grand Prize at the 4th Manga Taishou Awa",
        "cover_image_url": "/images/mangas/march_comes_in_like_a_lion.jpg",
        "mbrs_id": 31224,
        "price": 18.7
    },
    {
        "title": "Ashita no Joe: Fighting for Tomorrow",
        "author": "Ikki Kajiwara",
        "genre": "Drama, Slice of Life, Sports",
        "description": "A young drifter named Joe Yabuki wanders through the slums of Tokyo, but when the local ruffians try to give him a hard time he teaches them a rough lesson with his fists. The spectacle sparks a gleam in the eye of an old drunk who happens to be watching—Danpei Tange, a failed boxer and former coach who sees something special in the boy. He pleads with Joe to train with him off, but the cocky young fighter brushes him. Later, though, when Joe is arrested and put in a juvenile detention facility,",
        "cover_image_url": "/images/mangas/ashita_no_joe_fighting_for_tomorrow.jpg",
        "mbrs_id": 31303,
        "price": 18.9
    },
    {
        "title": "JoJo's Bizarre Adventure: Part 7–Steel Ball Run",
        "author": "Hirohiko Araki",
        "genre": "Action, Adventure, Drama, Mystery, Supernatural",
        "description": "Riders from around the world gather in the Wild West for the race of the century! Johnny Joestar, a former jockey paralyzed from the waist down, comes to spectate, and momentarily regains the ability to walk while watching a duel fought by Gyro Zeppeli. Desperate to learn more about this power, Johnny joins the race alongside Gyro and embarks on the most epic and bizarre race to ever cross the American frontier! (Source: VIZ Media)",
        "cover_image_url": "/images/mangas/jojo's_bizarre_adventure_part_7–steel_ball_run.jpg",
        "mbrs_id": 31706,
        "price": 19.2
    },
    {
        "title": "Natsume's Book of Friends",
        "author": "Yuki Midorikawa",
        "genre": "Drama, Supernatural",
        "description": "When Reiko was Takashi's age, she bound the names of demons and spirits in her Book of Friends, enslaving them to her capricious whim. Now Takashi is the owner of the book, and the creatures will do anything to get their names back. (Source: VIZ Media)",
        "cover_image_url": "/images/mangas/natsume's_book_of_friends.jpg",
        "mbrs_id": 31859,
        "price": 18.5
    },
    {
        "title": "Pandora Hearts",
        "author": "Jun Mochizuki",
        "genre": "Action, Adventure, Drama, Fantasy, Mystery, Psychological, Supernatural",
        "description": "The air of celebration surrounding fifteen-year-old Oz Vessalius&rsquo;s coming-of-age ceremony quickly turns to horror when he is condemned for a sin about which he knows nothing. He is thrown into an eternal, inescapable prison known as the Abyss from which there is no escape. There, he meets a young girl named Alice, who is not what she seems. Now that the relentless cogs of fate have begun to turn, do they lead only to crushing despair for Oz, or is there some shred of hope for him to grasp ",
        "cover_image_url": "/images/mangas/pandora_hearts.jpg",
        "mbrs_id": 33031,
        "price": 18.4
    },
    {
        "title": "Goodnight Punpun",
        "author": "Inio Asano",
        "genre": "Drama, Psychological, Slice of Life",
        "description": "Meet Punpun Punyama. He’s an average kid in an average town. He wants to win a Nobel Prize and save the world. He wants the girl he has a crush on to like him back. He wants to find some porn. That’s what he wants, but what does he get…? (Source: VIZ Media)",
        "cover_image_url": "/images/mangas/goodnight_punpun.jpg",
        "mbrs_id": 34632,
        "price": 18.8
    },
    {
        "title": "Ping Pong",
        "author": "Taiyou Matsumoto",
        "genre": "Drama, Psychological, Sports",
        "description": "Makoto “Smile” Tsukimoto and his friend Yutaka “Peco” Hoshino have been playing table tennis since they were kids, but as they enter high school, they find that the game has changed. Seeing potential in them that they themselves don’t fully realize, the coach recruits them for the school team. Bringing out their best will mean challenging the top players from rival schools in the summer tournament, including an ace Chinese exchange student who almost made the Olympic team. With the pressure on, ",
        "cover_image_url": "/images/mangas/ping_pong.jpg",
        "mbrs_id": 35744,
        "price": 18.5
    },
    {
        "title": "The Climber",
        "author": "Shinichi Sakamoto",
        "genre": "Adventure, Drama, Psychological, Sports",
        "description": "Transfer student Buntaro Mori starts his first day at his new school already on the administration’s radar. He’s withdrawn and sullen, and the teachers are just waiting for him to explode. When his annoying classmate Miyamoto promises to leave him alone forever if he climbs to the top of the school, Mori eagerly takes up the challenge and shocks everyone when he makes it all the way to the roof. Flushed with the victory of his first successful climb, Mori can’t resist the lure of the local peak,",
        "cover_image_url": "/images/mangas/the_climber.jpg",
        "mbrs_id": 37375,
        "price": 18.7
    },
    {
        "title": "Usogui",
        "author": "Toshio Sako",
        "genre": "Action, Psychological, Thriller",
        "description": "Driven by his desire for quick money, young Kaji gets involved with a loan shark and soon finds himself hounded by debt collectors. One day, a mysterious man named Baku Madarame appears before him. Calling himself a gambler, Baku boldly declares that he’ll help Kaji repay his debt—and descends into the world of underground casinos… (Source: MANGA MILLION)",
        "cover_image_url": "/images/mangas/usogui.jpg",
        "mbrs_id": 39982,
        "price": 18.6
    },
    {
        "title": "Billy Bat",
        "author": "Naoki Urasawa",
        "genre": "Drama, Mystery, Supernatural, Thriller",
        "description": "It’s 1949 Los Angeles, and Kevin Yamagata, a Japanese American comic book author, is drawing his bestselling character, Billy Bat: a quick-witted detective who is, unsurprisingly, a cartoon bat. Everything is going well for Kevin until he discovers an unfortunate truth: He may have unintentionally plagiarized his beloved character from a drawing he once saw in Japan. Devastated by the news, Kevin returns to war-torn Japan to find the drawing’s original artist . . . but the character’s origins tu",
        "cover_image_url": "/images/mangas/billy_bat.jpg",
        "mbrs_id": 41054,
        "price": 18.5
    },
    {
        "title": "A Bride's Story",
        "author": "Kaoru Mori",
        "genre": "Drama, Romance, Slice of Life",
        "description": "A Bride&rsquo;s Story tells the tale of a beautiful young bride in nineteenth-century Asia. At the age of twenty, Amir is sent to a neighboring town to be wed. But her surprise at learning her new husband, Karluk, is eight years younger than her is quickly replaced by a deep affection for the boy and his family. Though she hails from just beyond the mountains, Amir&rsquo;s clan had very different customs, foods, and clothes from what Karluk is used to. As the two of them learn more about each ot",
        "cover_image_url": "/images/mangas/a_bride's_story.jpg",
        "mbrs_id": 41514,
        "price": 18.5
    },
    {
        "title": "Chihayafuru",
        "author": "Yuki Suetsugu",
        "genre": "Drama, Romance, Sports",
        "description": "Chihaya is a girl in the sixth grade, still not old enough to even know the meaning of the word zeal. But one day, she meets Arata, a transfer student from rural Fukui prefecture. Though docile and quiet, he has an unexpected skill: his ability to play competitive karuta, a traditional Japanese card game. Chihaya is struck by his obsession with the game, along with his ability to pick out the right card and swipe it away before any of his opponents. However, Arata is transfixed by her as well, a",
        "cover_image_url": "/images/mangas/chihayafuru.jpg",
        "mbrs_id": 43245,
        "price": 18.6
    },
    {
        "title": "Space Brothers",
        "author": "Chuuya Koyama",
        "genre": "Sci-Fi, Slice of Life",
        "description": "Two brothers looked to the starry skies as children and made a promise ... Now, in the year 2025, the younger brother, Hibito, is carrying his out. He is an astronaut who has been selected as a crew member for mankind’s first long-term base on the moon. Meanwhile, the older brother, Mutta, has just been fired from his job and is unemployed, but decides to trust himself just one last time. A text message from Hibito sends him applying to be an astronaut too and shooting for the stars … (Source: K",
        "cover_image_url": "/images/mangas/space_brothers.jpg",
        "mbrs_id": 44483,
        "price": 18.6
    },
    {
        "title": "Kiichi VS",
        "author": "Hideki Arai",
        "genre": "Drama, Psychological",
        "description": "Ever more uncompromising in the face of injustice, Kiichi has become a star. Known around the world for shaking the Japanese establishment, he doesn't intend to stop there. Now at the head of a big company, between school of thought and mafia, whose members number in the thousands, he wants once again to get the population moving, even if it means provoking the powerful of the country! (Source: Editions Delcourt, translated)",
        "cover_image_url": "/images/mangas/kiichi_vs.jpg",
        "mbrs_id": 45547,
        "price": 18.5
    },
    {
        "title": "Kingdom",
        "author": "Yasuhisa Hara",
        "genre": "Action, Drama",
        "description": "Xin is a war orphan in a poor village in the kingdom of Qin. He has big dreams of becoming a great general, and when his best friend’s life is cut short by political machinations, Xin sets off to find a deposed ruler and help restore his place on the throne, while working his way up through the ranks of the Qin kingdom’s army to do what no one has ever done before—unify China. (Source: VIZ Media)",
        "cover_image_url": "/images/mangas/kingdom.jpg",
        "mbrs_id": 46765,
        "price": 18.9
    },
    {
        "title": "Yona of the Dawn",
        "author": "Mizuho Kusanagi",
        "genre": "Action, Adventure, Drama, Fantasy, Romance",
        "description": "A red-haired princess loses her family and her kingdom—now she must rise and fight for her throne! Princess Yona lives an ideal life as the only princess of her kingdom. Doted on by her father, the king, and protected by her faithful guard Hak, she cherishes the time spent with the man she loves, Su-won. But everything changes on her 16th birthday when tragedy strikes her family! Yona reels from the shock of witnessing a loved one's murder and having to fight for her life. With Hak's help, she f",
        "cover_image_url": "/images/mangas/yona_of_the_dawn.jpg",
        "mbrs_id": 51525,
        "price": 18.7
    },
    {
        "title": "Attack on Titan",
        "author": "Hajime Isayama",
        "genre": "Action, Drama, Fantasy, Mystery",
        "description": "In this post-apocalyptic sci-fi story, humanity has been devastated by the bizarre, giant humanoids known as the Titans. Little is known about where they came from or why they are bent on consuming mankind. Seemingly unintelligent, they have roamed the world for years, killing everyone they see. For the past century, what's left of man has hidden in a giant, three-walled city. People believe their 50-meter-high walls will protect them from the Titans, but the sudden appearance of an immense Tita",
        "cover_image_url": "/images/mangas/attack_on_titan.jpg",
        "mbrs_id": 53390,
        "price": 18.4
    },
    {
        "title": "Umineko When They Cry Episode 7: Requiem of the Golden Witch",
        "author": "Ryukishi07",
        "genre": "Drama, Mystery, Psychological, Supernatural, Thriller",
        "description": "The time for logical debate and magical feints has come to an end; the revelation of the truth about Beatrice the Golden Witch is at hand. To facilitate this, game master Bernkastel has chosen Will Wright the Mage-Hunter to step onto her board and answer a single question: Who killed Beatrice? Joining him in the game is Lion Ushiromiya, Krauss's firstborn and heir, whose role is a mystery in its own right. Will's line of questioning draws together the stray strands from all the previous games, t",
        "cover_image_url": "/images/mangas/umineko_when_they_cry_episode_7_requiem_of_the_golden_witch.jpg",
        "mbrs_id": 53900,
        "price": 18.7
    },
    {
        "title": "JoJo no Kimyou na Bouken: JoJolion",
        "author": "Hirohiko Araki",
        "genre": "Action, Adventure, Drama, Mystery, Supernatural",
        "description": "This part will take place in Morioh-Cho (the same town in Part 4: Diamond is Unbreakable), but in the alternative universe in which Steel Ball Run takes place. Following the Great East Japan earthquake, Morioh has been stricken by vast earthen protrusions known by the locals as Wall Eyes. Despite investigation, professional estimations are left empty. Meanwhile, the young girl Yasuho Hirose discovers a man buried within the ground, he possesses a distinctive star-shaped birthmark together with d",
        "cover_image_url": "/images/mangas/jojo_no_kimyou_na_bouken_jojolion.jpg",
        "mbrs_id": 55515,
        "price": 18.5
    },
    {
        "title": "Tokyo Ghoul",
        "author": "Sui Ishida",
        "genre": "Action, Horror, Mystery, Psychological, Supernatural",
        "description": "Shy Ken Kaneki is thrilled to go on a date with the beautiful Rize. But it turns out that she’s only interested in his body—eating it, that is. When a morally questionable rescue transforms him into the first half-human half-Ghoul hybrid, Ken is drawn into the dark and violent world of Ghouls, which exists alongside our own. (Source: VIZ Media) Note: Includes one extra chapter.",
        "cover_image_url": "/images/mangas/tokyo_ghoul.jpg",
        "mbrs_id": 63327,
        "price": 18.4
    },
    {
        "title": "Umineko When They Cry Episode 8: Twilight of the Golden Witch",
        "author": "Ryukishi07",
        "genre": "Drama, Fantasy, Mystery, Supernatural",
        "description": "It's time once again for the annual family gathering on Rokkenjima! Ange Ushiromiya is just getting over a cold, but that won't dampen her excitement at seeing her cousins again! Granddad couldn't be more thrilled to see his beloved grandchildren and throws a special Halloween party where everyone gets lots of treats! By lunchtime on the first day, the aunts and uncles are chatting up a storm, and the cousins are eagerly planning the afternoon's fun. It's the very picture of a happy family-one t",
        "cover_image_url": "/images/mangas/umineko_when_they_cry_episode_8_twilight_of_the_golden_witch.jpg",
        "mbrs_id": 64053,
        "price": 19.0
    },
    {
        "title": "Haikyu!!",
        "author": "Haruichi Furudate",
        "genre": "Comedy, Drama, Sports",
        "description": "Shouyou Hinata is out to prove that in volleyball you don’t need to be tall to fly! After losing his first and last volleyball match against Tobio Kageyama, “the King of the Court,” Shouyou Hinata swears to become his rival after graduating middle school. But what happens when the guy he wants to defeat ends up being his teammate?! (Source: VIZ Media) Notes: - Winner of the 61st Shogakukan Manga Award in the Shounen Category in 2017. - Includes two extra chapters.",
        "cover_image_url": "/images/mangas/haikyu!!.jpg",
        "mbrs_id": 65243,
        "price": 18.9
    },
    {
        "title": "One-Punch Man",
        "author": "ONE",
        "genre": "Action, Comedy, Sci-Fi, Supernatural",
        "description": "In this new action-comedy, everything about a young man named Saitama screams \"AVERAGE,&rdquo; from his lifeless expression, to his bald head, to his unimpressive physique. However, this average-looking fellow doesn't have your average problem... He's actually a superhero that's looking for tough opponents! The problem is, every time he finds a promising candidate he beats the snot out of them in one punch. Can Saitama finally find an evil villain strong enough to challenge him? Follow Saitama t",
        "cover_image_url": "/images/mangas/one-punch_man.jpg",
        "mbrs_id": 74347,
        "price": 18.5
    },
    {
        "title": "Land of the Lustrous",
        "author": "Haruko Ichikawa",
        "genre": "Action, Drama, Fantasy, Mystery, Psychological, Sci-Fi",
        "description": "In a world inhabited by crystalline lifeforms called The Lustrous, every unique gem must fight for their way of life against the threat of lunarians who would turn them into decorations. Phosphophyllite, the most fragile and brittle of gems, longs to join the battle. When Phos is instead assigned to complete a natural history of their world, it sounds like a dull and pointless task. But this new job brings Phos into contact with Cinnabar, a gem forced to live in isolation. Can Phos’s seemingly m",
        "cover_image_url": "/images/mangas/land_of_the_lustrous.jpg",
        "mbrs_id": 74489,
        "price": 18.9
    },
    {
        "title": "Kono Oto Tomare!",
        "author": "Amyuu Sakura",
        "genre": "Drama, Music, Romance",
        "description": "Since the graduation of the senior members of the club, Takezou ends up being the sole member of the \"Koto\" (traditional Japanese string instrument) club. Now that the new school year has begun, Takezou will have to seek out new members into the club, or the club will become terminated. Out of nowhere, a new member barges into the near-abandoned club room, demanding to join the club. How will Takezou be able to keep his club alive and deal with this rascal of a new member?",
        "cover_image_url": "/images/mangas/kono_oto_tomare!.jpg",
        "mbrs_id": 75143,
        "price": 18.8
    },
    {
        "title": "A Silent Voice",
        "author": "Yoshitoki Ooima",
        "genre": "Drama, Romance, Slice of Life",
        "description": "Based on a one-shot that won the 80th Weekly Shounen Magazine Newbie Best Mangaka Award. Shouya is a bully. When Shouko, a girl who can't hear, enters his elementary school class, she becomes their favorite target, and Shouya and his friends goad each other into devising new tortures for her. But the children's cruelty goes too far. Shouko is forced to leave the school, and Shouya ends up shouldering all the blame. Six years later, the two meet again. Can Shouya make up for his past mistakes, or",
        "cover_image_url": "/images/mangas/a_silent_voice.jpg",
        "mbrs_id": 85135,
        "price": 18.7
    },
    {
        "title": "Mob Psycho 100",
        "author": "ONE",
        "genre": "Action, Comedy, Drama, Psychological, Slice of Life, Supernatural",
        "description": "Do you or someone you know need an exorcist who works cheap? Reigen's your guy! What's his secret to busting ghosts while keeping prices low? Well, first, he's a fraud, and second, he pays the guy who's got the real psychic power—his student assistant Shigeo—less than minimum wage. Shigeo is an awkward but kind boy whose urge to help others and get along with them is bound up with the mental safety locks he's placed on his own emotions. Reigen knows he needs to exploit Shigeo to stay in business",
        "cover_image_url": "/images/mangas/mob_psycho_100.jpg",
        "mbrs_id": 85189,
        "price": 18.5
    },
    {
        "title": "Girls' Last Tour",
        "author": "Tsukumizu",
        "genre": "Adventure, Sci-Fi, Slice of Life",
        "description": "Civilization is dead, but Chito and Yuuri are still alive. So they hop aboard their beloved Kettenkrad motorbike and aimlessly wander the ruins of the world they once knew. Day after hopeless day, they look for their next meal and fuel for their ride. But as long as the two are together, even an existence as bleak as theirs has a ray or two of sunshine in it, whether they're sucking down their fill of soup or hunting for machine parts to tinker with. For two girls in a world full of nothing, the",
        "cover_image_url": "/images/mangas/girls'_last_tour.jpg",
        "mbrs_id": 85412,
        "price": 18.6
    },
    {
        "title": "ReLIFE",
        "author": "Sou Yayoi",
        "genre": "Comedy, Drama, Psychological, Romance, Slice of Life",
        "description": "When the responsibilities of being an adult and the ugly side of corporate bullying betrays one's childhood dreams, many would wish to return to their innocent childhood to relive their life and make the right decisions. Dumbfounded by the offer presented to him, 27-year-old Arata Kaizaki hopes to turn his life around through a once-in-a-lifetime opportunity. Returning home from his part-time job, Arata is persuaded by Ryou Yoake, an employee of ReLife Research Institute, into participating in a",
        "cover_image_url": "/images/mangas/relife.jpg",
        "mbrs_id": 85849,
        "price": 18.5
    },
    {
        "title": "19 Tian",
        "author": "Old Xian",
        "genre": "Comedy, Romance, Slice of Life",
        "description": "A group photo in kindergarten is the start of a lifetime friendship between Jian Yi and Zhan Zhengxi. They grew up together, and met good friends like He Tian and Mo Guanshan on campus. \"19 Days\" not only shows the relaxed and happy school days of the four, but is also a story in which the boys come to understand each other and help each other grow up. (Source: Tencent, translated)",
        "cover_image_url": "/images/mangas/19_tian.jpg",
        "mbrs_id": 85850,
        "price": 18.5
    },
    {
        "title": "Delicious in Dungeon",
        "author": "Ryouko Kui",
        "genre": "Adventure, Comedy, Drama, Fantasy",
        "description": "When young adventurer Laios and his company are attacked and soundly thrashed by a dragon deep in a dungeon, the party loses all its money and provisions...and a member! They're eager to go back and save her, but there is just one problem: If they set out with no food or coin to speak of, they're sure to starve on the way! But Laios comes up with a brilliant idea: \"Let's eat the monsters!\" Slimes, basilisks, and even dragons...none are safe from the appetites of these dungeon-crawling gourmands!",
        "cover_image_url": "/images/mangas/delicious_in_dungeon.jpg",
        "mbrs_id": 86082,
        "price": 18.8
    },
    {
        "title": "Wind Breaker",
        "author": "Yong-Seok Jo",
        "genre": "Action, Comedy, Drama, Romance, Sports",
        "description": "Jay's the perfect student. He's got straight As and he's the student body president. But after being coerced into joining the school's biking team, the Hummingbird Crew, he discovers a whole new world outside of studying. What new adventures will he face outside the comfort of his textbooks? (Source: WEBTOON) Notes: - Includes two extra chapters. - The work was cancelled after it was discovered that the artist had been tracing other people's art.",
        "cover_image_url": "/images/mangas/wind_breaker.jpg",
        "mbrs_id": 86099,
        "price": 18.5
    },
    {
        "title": "Bloom Into You",
        "author": "Nio Nakatani",
        "genre": "Drama, Romance, Slice of Life",
        "description": "Yuu has always loved shoujo manga and awaits the day she gets a love confession that sends her heart aflutter with bubbles and hearts, and yet when a junior high classmate confesses his feelings to her…she feels nothing. Disappointed and confused, Yuu enters high school still unsure how to respond. That’s when Yuu sees the beautiful student council president Nanami turn down a suitor with such maturity that she’s inspired to ask her for help. But when the next person to confess to Yuu is Nanami ",
        "cover_image_url": "/images/mangas/bloom_into_you.jpg",
        "mbrs_id": 86218,
        "price": 18.6
    },
    {
        "title": "Made in Abyss",
        "author": "Akihito Tsukushi",
        "genre": "Adventure, Drama, Fantasy, Horror, Sci-Fi",
        "description": "In an age when the corners of the world have been scoured for their secrets, only one place remains unexplored–a massive cave system known as the Abyss. Those who traverse its endless pits and labyrinth-like tunnels are known as Cave Raiders. A young orphan named Riko dreams of following in her mother’s footsteps as a Cave Raider, and when she meets a strange robot when exploring the Abyss, she’s one step closer to achieving her goal! (Source: Seven Seas Entertainment) Notes: - Includes the 5-ch",
        "cover_image_url": "/images/mangas/made_in_abyss.jpg",
        "mbrs_id": 86551,
        "price": 18.5
    },
    {
        "title": "Golden Kamuy",
        "author": "Satoru Noda",
        "genre": "Action, Adventure, Comedy, Drama",
        "description": "In the early twentieth century, Russo-Japanese War veteran Saichi “Immortal” Sugimoto scratches out a meager existence during the postwar gold rush in the wilderness of Hokkaido. When he stumbles across a map to a fortune in hidden Ainu gold, he sets off on a treacherous quest to find it. But Sugimoto is not the only interested party, and everyone who knows about the gold will kill to possess it! Faced with the harsh conditions of the northern wilderness, ruthless criminals and rogue Japanese so",
        "cover_image_url": "/images/mangas/golden_kamuy.jpg",
        "mbrs_id": 86559,
        "price": 18.6
    },
    {
        "title": "Ace of the Diamond Act II",
        "author": "Yuuji Terajima",
        "genre": "Slice of Life, Sports",
        "description": "I want to pitch to that mitt, just one more time… When Eijun Sawamura was just fifteen, he met someone who changed the course of his life forever—the catcher Kazuya Miyuki. Now, he's said goodbye to family and friends to travel to Seido High, where he can test his baseball skills alongside some of the best in the nation! (Source: K MANGA)",
        "cover_image_url": "/images/mangas/ace_of_the_diamond_act_ii.jpg",
        "mbrs_id": 86569,
        "price": 18.6
    },
    {
        "title": "Kaguya-sama: Love is War",
        "author": "Aka Akasaka",
        "genre": "Comedy, Psychological, Romance, Slice of Life",
        "description": "As leaders of their prestigious academy’s student council, Kaguya and Miyuki are the elite of the elite! But it’s lonely at the top… Luckily for them, they’ve fallen in love! There’s just one problem—they both have too much pride to admit it. And so begins the daily scheming to get the object of their affection to confess their romantic feelings first… Love is a war you win by losing. (Source: VIZ Media) Notes: - The first 10 chapters were published in Monthly Miracle Jump. It switched to Weekly",
        "cover_image_url": "/images/mangas/kaguya-sama_love_is_war.jpg",
        "mbrs_id": 86635,
        "price": 18.7
    },
    {
        "title": "Grand Blue Dreaming",
        "author": "Kenji Inoue",
        "genre": "Comedy, Romance, Slice of Life, Sports",
        "description": "After moving out on his own to a seaside town, Iori Kitahara makes a college debut he never anticipated. A new chapter of his life unfolds, full of diving with beautiful girls and shenanigans with a gaggle of lovable bastards! Idiot-expert Kenji Inoue and au naturel authority Kimitake Yoshioka bring you a glorious college tale filled with booze-fueled antics! (Source: Kodansha USA)",
        "cover_image_url": "/images/mangas/grand_blue_dreaming.jpg",
        "mbrs_id": 87395,
        "price": 18.9
    },
    {
        "title": "Tobaku Datenroku Kaiji: One Poker-hen",
        "author": "Nobuyuki Fukumoto",
        "genre": "Drama, Psychological, Thriller",
        "description": "Kaiji and Kazuya face off against each other in a high-stakes game of \"One Poker,\" a modified version of standard poker. Kazuya sets forth a gamble of 2,000,000,000 yen! How will Kaiji survive?! Chapter count for this arc is 101-254 in the original tankoubon.",
        "cover_image_url": "/images/mangas/tobaku_datenroku_kaiji_one_poker-hen.jpg",
        "mbrs_id": 89278,
        "price": 18.6
    },
    {
        "title": "Three Days of Happiness",
        "author": "Shouichi Taguchi",
        "genre": "Drama, Psychological, Romance, Supernatural",
        "description": "Kusunoki used to believe he was destined for great things. But now, approaching the age of twenty, he’s a completely mediocre college student with no motivation, no dreams, and no money. After learning he can sell his remaining years, he chooses to divest himself of all but his last three months. Spending this remaining time with his monitor, Miyagi, has Kusunoki truly destroyed his final chance to find happiness…or has he somehow found it? (Source: Yen Press) Note: Includes two extra chapters.",
        "cover_image_url": "/images/mangas/three_days_of_happiness.jpg",
        "mbrs_id": 97553,
        "price": 18.6
    },
    {
        "title": "Witch Hat Atelier",
        "author": "Kamome Shirahama",
        "genre": "Adventure, Drama, Fantasy",
        "description": "In a world where everyone takes wonders like magic spells and dragons for granted, Coco is a girl with a simple dream: she wants to be a witch. But everybody knows magicians are born, not made, and Coco was not born with a gift for magic. Resigned to her un-magical life, Coco is about to give up on her dream to become a witch … until the day she meets Qifrey, a mysterious, traveling magician. After secretly seeing Qifrey perform magic in a way she’s never seen before, Coco soon learns what every",
        "cover_image_url": "/images/mangas/witch_hat_atelier.jpg",
        "mbrs_id": 98263,
        "price": 18.7
    },
    {
        "title": "Toilet-Bound Hanako-kun",
        "author": "AidaIro",
        "genre": "Action, Comedy, Drama, Mystery, Romance, Supernatural",
        "description": "\"Hanako-san, Hanako-san... are you there?\" At Kamome Academy, rumors abound about the school's Seven Mysteries, one of which is Hanako-san. Said to occupy the third stall of the third floor girls' bathroom in the old school building, Hanako-san grants any wish when summoned. Nene Yashiro, an occult-loving high school girl who dreams of romance, ventures into this haunted bathroom... but the Hanako-san she meets there is nothing like she imagined! Kamome Academy's Hanako-san... is a boy! (Source:",
        "cover_image_url": "/images/mangas/toilet-bound_hanako-kun.jpg",
        "mbrs_id": 98842,
        "price": 18.5
    },
    {
        "title": "The Apothecary Diaries",
        "author": "Erika Ikeda",
        "genre": "Drama, Mystery",
        "description": "Maomao, a young woman trained in the art of herbal medicine, is forced to work as a lowly servant in the inner palace. Though she yearns for life outside its perfumed halls, she isn’t long for a life of drudgery! Using her wits to break a “curse” afflicting the imperial heirs, Maomao attracts the attentions of the handsome eunuch Jinshi and is promoted to attendant food taster. But Jinshi has other plans for the erstwhile apothecary, and soon Maomao is back to brewing potions and…solving mysteri",
        "cover_image_url": "/images/mangas/the_apothecary_diaries.jpg",
        "mbrs_id": 99022,
        "price": 18.5
    }
]

    created_count = 0
    skipped_count = 0

    for manga_data in mangas:
        # Check if manga already exists (by mbrs_id or title)
        if manga_data.get('mbrs_id'):
            existing = Manga.objects.filter(mbrs_id=manga_data['mbrs_id']).first()
        else:
            existing = Manga.objects.filter(title=manga_data['title']).first()

        if existing:
            print(f"  [SKIP] Skipped: {manga_data['title']} (already exists)")
            skipped_count += 1
            continue

        # Create manga
        manga = Manga.objects.create(
            title=manga_data['title'],
            author=manga_data['author'],
            genre=manga_data['genre'],
            description=manga_data.get('description', ''),
            cover_image_url=manga_data['cover_image_url'],
            rental_price_per_day=manga_data['price'],
            mbrs_id=manga_data.get('mbrs_id'),
            is_active=True
        )

        # Create 3 copies for each manga
        for i in range(3):
            MangaCopy.objects.create(
                manga=manga,
                serial_no=f"{manga.title[:3].upper()}-{manga.id:04d}-{i+1:02d}",
                status=MangaCopy.Status.AVAILABLE
            )

        print(f"  [OK] Created: {manga.title} (3 copies)")
        created_count += 1

    print(f"\nSeeding completed!")
    print(f"  - Created: {created_count} manga")
    print(f"  - Skipped: {skipped_count} manga")
    print(f"  - Total copies: {created_count * 3}")

if __name__ == "__main__":
    seed_anilist_manga()
