# Generated by Django 5.2.17 on 2026-08-21 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('algorithm', models.CharField(choices=[('MBCGCN', 'MB-CGCN (Two Behaviors)'), ('LIGHTGCN', 'LightGCN'), ('MF', 'Matrix Factorization'), ('POPULAR', 'Popular Items')], max_length=50)),
                ('traffic_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('num_users', models.IntegerField(default=0)),
                ('num_items', models.IntegerField(default=0)),
                ('num_cart_interactions', models.IntegerField(default=0)),
                ('num_rent_interactions', models.IntegerField(default=0)),
                ('epochs', models.IntegerField(default=0)),
                ('final_recall_at_10', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('final_ndcg_at_10', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IMPRESSION', 'Recommendation Shown'), ('CLICK', 'Manga Clicked'), ('ADD_TO_CART', 'Added to Cart'), ('RENTAL', 'Rented')], max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.abtestvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ABTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_assignments', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.abtestvariant')),
            ],
            options={
                'unique_together': {('user', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CLICK', 'Viewed Manga Detail'), ('ADD_CART', 'Added to Cart'), ('RENT', 'Rented')], max_length=20)),
                ('source', models.CharField(choices=[('BROWSE', 'Browse/Home'), ('SEARCH', 'Search'), ('RECOMMENDATION', 'For You Page'), ('PROFILE', 'Profile/History'), ('DIRECT', 'Direct Link')], default='DIRECT', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='rentals.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type'], name='rentals_use_user_id_7fc545_idx'), models.Index(fields=['manga', 'event_type'], name='rentals_use_manga_i_bd901f_idx'), models.Index(fields=['created_at'], name='rentals_use_created_af9552_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user', 'manga')},
            },
        ),
    ]
