# Generated by Django 5.2.12 on 2026-03-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangacopy',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('RENTED', 'Rented'), ('LOST', 'Lost'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=50),
        ),
    ]
