# Generated by Django 5.2.17 on 2026-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_abtestvariant_modeltraininglog_abtestevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
