# Generated by Django 5.2.12 on 2026-03-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_finelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover_image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='covers/'),
        ),
    ]
