# Generated by Django 5.2.12 on 2026-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_manga_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='rental_price_per_day',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
            preserve_default=False,
        ),
    ]
