# Generated by Django 5.2.17 on 2026-08-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_modelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='active_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rentals.modeltraininglog'),
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='graph_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='weight_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='active_version',
            field=models.CharField(choices=[('v1', 'MB-CGCN v1 (CART+RENT)'), ('v2', 'MB-CGCN v2 (CLICK+CART+RENT)')], default='v1', max_length=10),
        ),
    ]
