# Generated by Django 5.2.12 on 2026-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_manga_rental_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
