# Generated by Django 5.2.12 on 2026-03-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_manga_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='due_at',
        ),
    ]
