# Generated by Django 5.2.12 on 2026-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_mangareview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangareview',
            name='comment',
        ),
        migrations.AddField(
            model_name='manga',
            name='mbrs_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
